### ISSUE TITLE
Building with Qt 5.7 fails

### ISSUE THREAD

**Issue by josch1710** [jzatarski/RespeQt#40]
I initially only installed the Qt 5.7 toolkit.
The generated UI code, references the wrong headers, for example.
I could build the application, by changing all the culprits. But after changing the UI, I anticipate to do it all over again.
For future proofing, this should be changed.

**Comment by josch1710** [comment]
Can't replicate it at the moment, so I'm closing this

**Comment by jzatarski** [comment]
perhaps you were using old versions of the automatically generated ui related headers? I know I had issues with this when trying to build RespeQt before, a make clean may have fixed the issue, although I remember manually deleting the headers which were giving issues.
